app:
  title: "AI Workforce Analysis"
  page_icon: "📊"
  layout: "wide"
  initial_sidebar_state: "expanded"
  theme:
    primaryColor: "#1f77b4"
    backgroundColor: "#ffffff"
    secondaryBackgroundColor: "#f0f2f6"
    textColor: "#262730"
    font: "sans serif"

model:
  model_dir: "models"
  random_state: 42
  test_size: 0.2
  n_estimators: 100
  model_params:
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1

data:
  required_columns:
    EmployeeNumber: "int64"
    Age: "int64"
    Department: "object"
    JobRole: "object"
    Salary: "int64"
    YearsAtCompany: "int64"
    JobSatisfaction: "int64"
    WorkLifeBalance: "int64"
    PerformanceRating: "int64"
    Attrition: "object"
    Education: "int64"
    EducationField: "object"
    Gender: "object"
    MaritalStatus: "object"
    NumCompaniesWorked: "int64"
    TotalWorkingYears: "int64"
    TrainingTimesLastYear: "int64"
    YearsInCurrentRole: "int64"
    YearsSinceLastPromotion: "int64"
    YearsWithCurrManager: "int64"
  date_columns:
    - "HireDate"
    - "TerminationDate"
  categorical_columns:
    - "Department"
    - "JobRole"
    - "EducationField"
    - "Gender"
    - "MaritalStatus"
    - "Attrition"
  numeric_columns:
    - "Age"
    - "Salary"
    - "YearsAtCompany"
    - "JobSatisfaction"
    - "WorkLifeBalance"
    - "PerformanceRating"
    - "Education"
    - "NumCompaniesWorked"
    - "TotalWorkingYears"
    - "TrainingTimesLastYear"
    - "YearsInCurrentRole"
    - "YearsSinceLastPromotion"
    - "YearsWithCurrManager"
  preprocessing_steps:
    - "handle_missing_values"
    - "convert_dates"
    - "encode_categorical"
    - "scale_numeric"

api_key: null
debug: false
log_level: "INFO"
log_dir: "logs" 